services:
  nginx:
    image: nginx:1.19-alpine
    container_name: ea_uc-nginx
    restart: unless-stopped
    ports:
      - 3080:80
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
